server {
    listen 80;

    # 访问前端资源
    location /fe/ {
        proxy_pass http://localhost:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 访问后端接口
    location /api/ {
        proxy_pass http://localhost:90/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 兜底使用
    location / {
        root /usr/share/nginx/html;  # 确保这个路径存在并包含index.html
        try_files $uri $uri/ /index.html;
    }
}