/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/auto-import/': RouteRecordInfo<'/auto-import/', '/auto-import', Record<never, never>, Record<never, never>>,
    '/axios/': RouteRecordInfo<'/axios/', '/axios', Record<never, never>, Record<never, never>>,
    '/fe/settle/': RouteRecordInfo<'/fe/settle/', '/fe/settle', Record<never, never>, Record<never, never>>,
    '/settle/': RouteRecordInfo<'/settle/', '/settle', Record<never, never>, Record<never, never>>,
    '/unocss/': RouteRecordInfo<'/unocss/', '/unocss', Record<never, never>, Record<never, never>>,
  }
}
